app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  client:
    github-api-url: ${GITHUB_API_URL:https://api.github.com}
    stackoverflow-api-url: ${STACKOVERFLOW_API_URL:https://api.stackexchange.com/2.3}
    bot-api-url: ${BOT_API_URL:http://localhost:8090}
  database-access-type: jpa

spring:
  application:
    name: scrapper
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/scrapper}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
