app:
  telegram-token: ${TELEGRAM_TOKEN}
  client:
    scrapper-api-url: ${SCRAPPER_API_URL:http://localhost:8080}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
